services:
  # 🌐 Frontend (Node.js)
  - type: web
    name: my-web-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    branch: main
    autoDeploy: true
    region: oregon

  # ⚙️ Backend (Flask API)
  - type: web
    name: my-backend
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --force-reinstall numpy==1.26.4 --no-cache-dir
      pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    runtime: python
    branch: main
    autoDeploy: true
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
